### ISSUE TITLE
error

### ISSUE THREAD

**Issue by amanshr72** [SajeebChakraborty/Restaurant_Ecommerce_System_Laravel#1]
- SQL error at the time of running the project, after running all migration & seeders.
- session not generating records. so that HomeController index fun can return view.

![image](https://user-images.githubusercontent.com/92160310/221187187-62f3b56c-eefe-42a8-93f0-888bb7e4e276.png)

**Comment by SajeebChakraborty** [comment]
contact with me for solution

https://www.facebook.com/sajeeb.chakraborty

**Comment by SajeebChakraborty** [comment]
All issue solved. Please check my repository again. Find out my sql file (named-rms2.sql) and attach it with your database. Then enjoy with my project.
